---
- name: Install Apache web server
  hosts: localhost
  become: true
  # play made some changes in git bash

  tasks:
    - name: Install Apache
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
