---
- name: Configure firewall with firewalld
  hosts: all
  become: true
# this play belong to firewall 
  tasks:
    - name: Ensure firewalld is installed
      yum:
        name: firewalld
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Open HTTP (port 80)
      firewalld:
        service: http
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open HTTPS (port 443)
      firewalld:
        service: https
        permanent: yes
        state: enabled
        immediate: yes

    - name: Open custom TCP port (e.g., 8080)
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
        immediate: yes
